name: edu_connect
services:
  postgres:
    image: postgres:latest
    container_name: service_auth_db
    restart: always
    env_file:
      - ./servico-autenticacao/.env
    ports:
      - '5432:5432'
